### ISSUE TITLE
store methods do not call back on db error

### ISSUE THREAD

**Issue by iantocristian** [senecajs/seneca-mongo-store#10]
error handler should cb?

**Comment by seanrucker** [comment]
I am noticing this as well. I'm using unique indexes to prevent duplicates. I can't catch the "MongoError: E11000 duplicate key error". After a few seconds I get a timeout.

**Comment by gkubisa** [comment]
I just added the missing callback call in my pull request. The unit tests still have to be extended to cover error scenarios.
