### ISSUE TITLE
Update to newer mongo driver?

### ISSUE THREAD

**Issue by cheshirecatalyst** [senecajs/seneca-mongo-store#14]
Is this possible anytime soon?

**Comment by mcdonnelldean** [comment]
@cheshirecatalyst This is coming real soon, apologies for the delay. Going forward it will be much quicker.

**Comment by jluchiji** [comment]
+1 Having a newer version of mongo driver would be immensely helpful. Especially now that new mongoldb driver returns promises out of the box.

**Comment by kiakj** [comment]
+1 Is there any ETA for this?

**Comment by mcdonnelldean** [comment]
This is merged. An update will go out once we wire up a testing rig (next few working days).
