### ISSUE TITLE
Timeout Error: How to remove using ID?

### ISSUE THREAD

**Issue by qnimate** [senecajs/seneca-mongo-store#18]
Here is the code
```
seneca.add({role: "coupons-store", cmd: "delete"}, function(args, respond){
	var coupons = seneca.make$("coupons");
	coupons.remove$({id: args.id}, function(err, entity){
		if(err) return respond(error);

		respond(null, {value: true});	
	});
});
```

Seems like I am passing the ID wrong way. It gives timeout error. But the document gets deleted from the `coupons` collection.

Please help me to fix this.

**Comment by chafnan** [comment]
Have you tried to pass the id directly as a string and not as an object.  Here is an example from the [seneca docs](http://senecajs.org/tutorials/understanding-data-entities.html):

```
var id = '...'
var foo_entity = seneca.make('foo')
foo_entity.remove$( id, function(err){ ... })
```

**Comment by mcdonnelldean** [comment]
This ^
