### ISSUE TITLE
Does not work with latest versions of node.js

### ISSUE THREAD

**Issue by aikssen** [senecajs/seneca-mongo-store#36]
Is not possible to get working this plugin with the latest versions of node.js
It Was tested with v6.0.0 and v4.4.3 of node.js

**Comment by mcdonnelldean** [comment]
@aikssen I know for sure it won't work with 6 as we are testing that now. It should work with 4.x. There will be tests added soon to figure out the issues.

**Comment by luhtonen** [comment]
I was doing experiments with this plugin using latest Node.js version `v6.3.1` and it's working. Plugin producing `{ Error: Cannot find module '../build/Release/bson'` error because it is still using updated dependencies, but I was able to insert data into Mongo and was able to query it from it.

**Comment by mihaidma** [comment]
The travis tests pass on Node 10, 12, 4, 5, 6 for both Seneca 1.x and 2.x.
A passing full build on master: https://travis-ci.org/senecajs/seneca-mongo-store/builds/150052267

I'll close this, please reopen if issues persist.
