### ISSUE TITLE
Update seneca-test-store to 1.x.x

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca-mongo-store#50]
Currently the seneca-test-store dependency is 0.3.0 (this is the store interface version it implements)
Needs to be updated to 1.0.0 or later, these test versions include a lot more tests.

**Comment by rjrodger** [comment]
update latest!

**Comment by lilsweetcaligula** [comment]
@rjrodger This issue can be resolved once `seneca-store-test@3.2.0` has been released.
