### ISSUE TITLE
How do I update / modify a document in mongo using seneca-mongo-store? 

### ISSUE THREAD

**Issue by soundaryathiagarajan** [senecajs/seneca-mongo-store#52]
Hi, 

I have tried inserting and deleting a document using seneca-mongo-store and successfully able to insert and delete data in mongo.. How do I update / modify a document from mongo? 

const seneca = require('seneca')();
seneca.use('entity');
seneca.use('mongo-store', {
			name: 'test',
			host: 'localhost',
			port: 27017
		});

var Device = null;

module.exports =
{	
	connect : function(done) {
		seneca.use('mongo-store', {
			name: 'test',
			host: 'localhost',
			port: 27017
		});
		console.log('connected');
		//if(err) { console.error(err); data({result : 'failed'}) }
		seneca.ready(done);
	},

	addDevice : function(data,done){
        console.log('In addDevice function')
        var newDevice = seneca.make$('sdeviceabccd')
		newDevice.data = data
		console.log("data entered..")
        newDevice.save$(function (err,newDevice) {
			console.log("newDevice:" +newDevice.id)
			if(err) { console.log("newDevice") } 
			done({result : 'success'});
        });
    },	

	 //Deleting the entry from DB
    deleteDevice : function(data,done){
		console.log(data)
		console.log('printed datad..')
		var newData = seneca.make$('sdeviceabccd')
		newData.remove$({'id': '57b2fce913aaa81998573fe5'}, function (err, newData) { 
			console.log('deleted data'); 
			done({result : 'success'}); 
		});
	},		

	ListDevice : function(done) { 
		console.log('listed..');
		var sounDa = seneca.make$('sdeviceabccd');
	    sounDa.list$(function (err, sounDa) { 	
		console.log('data listed..' +sounDa)
		if(err) { 
			console.log("listed dev") 
		} 
		done({result : 'success'}); 
	})
},
}
can anyone tell me how do I update using the same? I dont find option for update$ in github. 

**And this is the main file which I am executing:** 

device = require('./souhom');

	device.connect(function(done){
		console.log('connected');
		data = 'devicedata'
	
	device.addDevice(data,function(retval){
		console.log(retval.result); 
	
	device.deleteDevice({ "_id" : "57b2fd09b95a6719acf5f38d"},function(ret) {
		console.log(ret);
		console.log("-----");
	device.ListDevice(function(ret) {
		console.log(ret.result);
});   
}); 
});
});

**Comment by soundaryathiagarajan** [comment]
here is the function I wrote for updateDevice: 
    updateDevice : function(done) { 
	console.log('.. update')
	console.log(data)
	var soundar = seneca.make$('sdeviceabcc').find({ "_id" : "57b2febabf2d231a79bde760"})
	  soundar.each(function(err, data) {		
		if(data != null) {
			done({result : "data found"})
			console.log("data" +data)
		} else { 
			console.log("empty")
			}
		});
},

but still doesnt seem like working.

**Comment by mihaidma** [comment]
@soundaryathiagarajan see here samples on how to use the stores: https://github.com/senecajs/seneca-store-test/blob/master/store-test.js#L238

**Comment by soundaryathiagarajan** [comment]
Thanks Mihaidma. I am able to update / modify now.
